"""add_category_to_courses

Revision ID: 7feb7070683c
Revises: d4ea1c4bee91
Create Date: 2026-04-27 01:36:18.201208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7feb7070683c'
down_revision: Union[str, Sequence[str], None] = 'd4ea1c4bee91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'category')
    # ### end Alembic commands ###
