"""add_transcript_to_lessons

Revision ID: 9435aec09072
Revises: f8327c75f144
Create Date: 2026-06-02 01:06:09.711251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9435aec09072'
down_revision: Union[str, Sequence[str], None] = 'f8327c75f144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'transcript')
    # ### end Alembic commands ###
