"""Add stripe_price_id to Plan

Revision ID: d4ea1c4bee91
Revises: c2a7e9f81234
Create Date: 2026-04-21 23:19:38.897617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ea1c4bee91'
down_revision: Union[str, Sequence[str], None] = 'c2a7e9f81234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('stripe_price_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'stripe_price_id')
    # ### end Alembic commands ###
