"""remove icon from category

Revision ID: f8327c75f144
Revises: e5f6a7b8c9d0
Create Date: 2026-05-03 15:51:17.319863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8327c75f144'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # icon column was never added in the categories table creation migration — no-op
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
